const db = globalThis.__B44_DB__ || { auth:{ isAuthenticated: async()=>false, me: async()=>null }, entities:new Proxy({}, { get:()=>({ filter:async()=>[], get:async()=>null, create:async()=>({}), update:async()=>({}), delete:async()=>({}) }) }), integrations:{ Core:{ UploadFile:async()=>({ file_url:'' }) } } };

import { cultureImages } from './images';
export const arabicPhrases=[
{arabic:'مرحبا',translit:'Marhaba',meaning:'Hello / Welcome',context:'A common greeting used in everyday interactions.'},
{arabic:'شكراً',translit:'Shukran',meaning:'Thank you',context:'Used to express gratitude in any situation.'},
{arabic:'السلام عليكم',translit:'As-salamu alaykum',meaning:'Peace be upon you',context:'A formal Islamic greeting used between Muslims.'},
{arabic:'وعليكم السلام',translit:'Wa alaykum as-salam',meaning:'And peace be upon you too',context:'The standard response to "As-salamu alaykum".'},
{arabic:'صباح الخير',translit:'Sabah al-khair',meaning:'Good morning',context:'Used as a morning greeting until midday.'},
{arabic:'مساء الخير',translit:'Masa al-khair',meaning:'Good evening',context:'Used as an evening greeting.'},
{arabic:'أهلاً وسهلاً',translit:'Ahlan wa sahlan',meaning:'Welcome',context:'A warm greeting welcoming guests and visitors.'},
{arabic:'من فضلك',translit:'Min fadlak',meaning:'Please',context:'Used when making a polite request.'},
{arabic:'نعم',translit:'Naam',meaning:'Yes',context:'A simple affirmative response.'},
{arabic:'لا',translit:'La',meaning:'No',context:'A simple negative response.'},
{arabic:'كيف حالك؟',translit:'Kayf halak?',meaning:'How are you?',context:'A common question asking about someone\'s wellbeing.'},
{arabic:'بخير، الحمد لله',translit:'Bikhair, alhamdulillah',meaning:'Fine, praise be to God',context:'A common response indicating wellbeing and gratitude.'}
];

export const placeNames=[
{name:'Abu Dhabi',arabic:'أبوظبي',meaning:'The name "Abu Dhabi" is traditionally associated with "Father of the Gazelle," reflecting the abundance of gazelles that once roamed the area.',topic:'Emirate Name'},
{name:'Dubai',arabic:'دبي',meaning:'The origin of "Dubai" is debated. Some scholars associate it with the Arabic word "daba" meaning "to creep or crawl," possibly referring to the slow movement of the creek. Others link it to a type of locust.',topic:'Emirate Name'},
{name:'Al Ain',arabic:'العين',meaning:'"Al Ain" means "The Spring" or "The Water Source" in Arabic, reflecting the natural springs and oasis that sustained the city for thousands of years.',topic:'City Name'},
{name:'Sharjah',arabic:'الشارقة',meaning:'"Sharjah" is traditionally associated with "the rising sun" or "eastern," reflecting its geographic position relative to nearby settlements.',topic:'Emirate Name'},
{name:'Fujairah',arabic:'الفجيرة',meaning:'The name "Fujairah" is traditionally associated with the Arabic root meaning "to break through" or "to emerge," possibly referring to the mountain passes that lead to the coast.',topic:'Emirate Name'},
{name:'Ras Al Khaimah',arabic:'رأس الخيمة',meaning:'"Ras Al Khaimah" means "Head of the Tent" in Arabic, possibly referring to a tent-shaped landmark or a prominent headland.',topic:'Emirate Name'},
{name:'Umm Al Quwain',arabic:'أم القيوين',meaning:'"Umm Al Quwain" is traditionally associated with "Mother of the Two Powers," possibly referring to the area\'s strong position in trade or its dual maritime and agricultural economy.',topic:'Emirate Name'},
{name:'Jebel',arabic:'جبل',meaning:'"Jebel" means "mountain" in Arabic, used in place names like Jebel Jais and Jebel Hafeet.',topic:'Geographic Term'},
{name:'Wadi',arabic:'وادي',meaning:'"Wadi" means "valley" or "dry riverbed" in Arabic, referring to the valleys that carry water during rare rainfall.',topic:'Geographic Term'},
{name:'Falaj',arabic:'فلج',meaning:'"Falaj" refers to the traditional underground water channel system used for irrigation in the UAE for over 3,000 years.',topic:'Geographic Term'},
{name:'Souq',arabic:'سوق',meaning:'"Souq" means "market" or "marketplace" in Arabic, referring to the traditional trading areas found in every UAE town.',topic:'Cultural Term'},
{name:'Majlis',arabic:'مجلس',meaning:'"Majlis" means "place of sitting" in Arabic, referring to the traditional gathering space where guests are received and community matters are discussed.',topic:'Cultural Term'}
];

export const heritage=[
{title:'Falconry',arabic:'الصقارة',icon:'🦅',image:'https://media.db.com/images/public/6a7c883244b0c2e59e05c109/1e4b20f35_generated_image.png',description:'Falconry is a traditional hunting practice using trained falcons, passed down through generations of Bedouin communities.',history:'Falconry has been practiced in the Arabian Peninsula for over 4,000 years. Bedouin hunters used falcons to catch prey in the desert, supplementing their diet with fresh meat. The practice required deep knowledge of the birds and their behavior.',significance:'Falconry represents the deep connection between Emirati culture and the desert environment. UNESCO inscribed falconry on the Representative List of the Intangible Cultural Heritage of Humanity in 2021.',today:'Today, falconry is a cherished sport and cultural tradition. The UAE hosts international falconry festivals and has established hospitals dedicated to falcon health.',didYouKnow:'The UAE has dedicated falcon hospitals, including the Abu Dhabi Falcon Hospital, one of the largest of its kind in the world.'},
{title:'Camel Racing',arabic:'سباق الهجن',icon:'🐪',image:'https://images.unsplash.com/photo-1779032369221-5a0861a3534e?auto=format&fit=crop&w=1200&q=85',description:'Camel racing is a traditional sport and cultural event that has been modernized while preserving its heritage.',history:'Camel racing has been part of Bedouin culture for centuries, originally as informal competitions between tribes. In the modern era, it has become an organized sport with dedicated tracks and facilities.',significance:'Camel racing preserves an important aspect of Bedouin heritage and remains a popular cultural event, especially during winter months.',today:'Modern camel racing in the UAE uses robot jockeys instead of human riders, a technological innovation that improved safety while preserving the tradition.',didYouKnow:'Modern camel racing in the UAE uses robot jockeys controlled by operators following in vehicles, replacing child jockeys and improving safety.'},
{title:'Pearl Diving',arabic:'الغوص على اللؤلؤ',icon:'🦪',image:'https://media.db.com/images/public/6a7c883244b0c2e59e05c109/9226cce17_generated_image.png',description:'Pearl diving was the economic backbone of UAE coastal communities before the discovery of oil.',history:'For centuries, pearl diving was the main source of income for coastal communities. Divers would hold their breath to collect oysters from the sea floor, facing dangers including drowning and shark attacks. The pearling season ran from June to September.',significance:'Pearl diving shaped the culture, economy, and social structure of UAE coastal communities. It fostered trade relationships across the Gulf and beyond.',today:'While commercial pearl diving ended with the rise of cultured pearls in the 1930s, the heritage is preserved through museums, cultural events, and initiatives like Suwaidi Pearls in RAK.',didYouKnow:'Pearl divers could stay underwater for up to two minutes, diving to depths of over 30 metres without any breathing equipment.'},
{title:'Dhow Building',arabic:'بناء الداو',icon:'⛵',image:'https://images.unsplash.com/photo-1784821441898-9e067f1c95e4?auto=format&fit=crop&w=1200&q=85',description:'Dhow building is the traditional craft of constructing wooden boats used for trade, fishing, and pearling.',history:'Dhow building has been practiced in the UAE for centuries. Shipwrights used traditional tools and techniques, working without blueprints, relying on knowledge passed down through generations. The boats were essential for trade across the Gulf and Indian Ocean.',significance:'Dhow building represents the maritime heritage of the UAE and the ingenuity of traditional craftsmen who built seaworthy vessels using simple tools.',today:'Traditional dhow building yards still operate in the UAE, including in Ajman and Dubai, preserving the craft while adapting to modern needs.',didYouKnow:'Traditional dhow builders worked without written plans, relying entirely on memory and experience passed down through generations.'},
{title:'Traditional Weaving (Sadu)',arabic:'السدو',icon:'🧶',image:'https://images.unsplash.com/photo-1569909115134-a0426936c879?auto=format&fit=crop&w=1200&q=85',description:'Sadu is the traditional weaving of the Bedouin, producing decorative fabrics from sheep\'s wool and goat hair.',history:'Sadu weaving was practiced by Bedouin women who created tents, cushions, and decorative items from animal wool. The craft required skill in spinning, dyeing, and weaving, and patterns carried cultural meanings.',significance:'Sadu weaving is a UNESCO-recognized intangible cultural heritage, representing the artistic and practical traditions of Bedouin life.',today:'Sadu weaving is preserved through cultural programs and exhibitions, with efforts to teach the craft to new generations.',didYouKnow:'Sadu weaving was inscribed on the UNESCO List of Intangible Cultural Heritage in Need of Urgent Safeguarding in 2011.'},
{title:'Henna',arabic:'الحناء',icon:'🌿',image:'https://images.unsplash.com/photo-1720798298994-bf41cb26ba31?auto=format&fit=crop&w=1200&q=85',description:'Henna is a traditional body art using a paste made from the henna plant, applied during celebrations and special occasions.',history:'Henna has been used in the Arabian Peninsula for centuries, with intricate designs applied during weddings, Eid celebrations, and other festive occasions. The art is traditionally passed from older to younger women.',significance:'Henna represents an important cultural tradition of adornment and celebration, particularly significant at weddings and festivals.',today:'Henna remains an essential part of UAE celebrations, with professional henna artists creating increasingly elaborate designs.',didYouKnow:'Henna paste is made from the dried leaves of the henna plant, which releases a natural dye that stains the skin temporarily.'}
];

export const cuisine=[
{name:'Machboos',arabic:'مجبوس',image:'https://images.unsplash.com/photo-1778785241914-7f75ca16a92d?auto=format&fit=crop&w=1200&q=85',description:'A spiced rice dish with meat or chicken, considered one of the most popular traditional Emirati dishes.',ingredients:'Basmati rice, meat or chicken, onions, dried lemon (loomi), saffron, cardamom, cinnamon, turmeric',history:'Machboos has been a staple of Emirati cuisine for generations, traditionally served at family gatherings and celebrations.',occasions:'Served at weddings, Eid celebrations, and Friday family lunches.',didYouKnow:'The dried lemon (loomi) used in Machboos gives the dish its distinctive tangy flavor and is a key ingredient in Gulf cuisine.'},
{name:'Harees',arabic:'هريس',image:'https://media.db.com/images/public/6a7c883244b0c2e59e05c109/7e91ed037_generated_image.png',description:'A porridge-like dish made from wheat and meat, slow-cooked until smooth and creamy.',ingredients:'Crushed wheat, meat (usually chicken or lamb), salt, ghee',history:'Harees is one of the oldest dishes in Emirati cuisine, traditionally prepared during Ramadan and at weddings. The slow cooking process can take several hours.',occasions:'Especially popular during Ramadan and at wedding celebrations.',didYouKnow:'Harees is cooked slowly for hours until the wheat and meat merge into a smooth consistency, requiring patience and skill.'},
{name:'Luqaimat',arabic:'لقيمات',image:'https://images.unsplash.com/photo-1758779527897-bb4097eb0445?auto=format&fit=crop&w=1200&q=85',description:'Sweet dumplings made from a yeast batter, fried and drizzled with date syrup (dibs).',ingredients:'Flour, yeast, sugar, cardamom, saffron, date syrup (dibs)',history:'Luqaimat is a beloved traditional dessert, often prepared during Ramadan and festive occasions. The name means "small bites" in Arabic.',occasions:'Served during Ramadan, Eid, and family celebrations.',didYouKnow:'The name "Luqaimat" means "small bites" in Arabic, reflecting the bite-sized nature of these sweet dumplings.'},
{name:'Balaleet',arabic:'بلاليط',image:'https://media.db.com/images/public/6a7c883244b0c2e59e05c109/477ad6d31_generated_image.png',description:'A sweet and savory dish of vermicelli noodles topped with a thin omelette, flavored with cardamom and saffron.',ingredients:'Vermicelli, sugar, cardamom, saffron, ghee, eggs',history:'Balaleet is traditionally served for breakfast, especially during Ramadan and Eid. The combination of sweet noodles with savory omelette is distinctive to Gulf cuisine.',occasions:'Served for breakfast during Ramadan and Eid celebrations.',didYouKnow:'Balaleet uniquely combines sweet vermicelli with a savory omelette on top, a distinctive feature of Gulf breakfast cuisine.'},
{name:'Arabic Coffee (Gahwa)',arabic:'قهوة عربية',image:'https://images.unsplash.com/photo-1754874398289-70b375a6f27f?auto=format&fit=crop&w=1200&q=85',description:'Traditional Arabic coffee flavored with cardamom, served in small cups as a symbol of hospitality.',ingredients:'Lightly roasted coffee beans, cardamom, saffron (sometimes), water',history:'Arabic coffee is central to Emirati hospitality, traditionally served to guests as a sign of welcome and respect. The preparation and serving of gahwa is a UNESCO-recognized cultural practice.',occasions:'Served to guests at all times, and especially at weddings, funerals, and social gatherings.',didYouKnow:'Arabic coffee is traditionally served in small cups without handles, and the host continues refilling until the guest gently shakes the cup to indicate they have had enough.'},
{name:'Dates',arabic:'تمر',image:'https://images.unsplash.com/photo-1629738601425-494c3d6ba3e2?auto=format&fit=crop&w=1200&q=85',description:'Dates are the fruit of the date palm and hold immense cultural and nutritional significance in the UAE.',ingredients:'Fresh or dried dates, sometimes stuffed with nuts or filled with sweet fillings',history:'Dates have been a staple food in the Arabian Peninsula for thousands of years, providing essential nutrition in the desert environment. The date palm is the national tree of the UAE.',occasions:'Served with Arabic coffee to guests, during Ramadan for breaking the fast, and at all celebrations.',didYouKnow:'The UAE has over 40 varieties of dates, and the date palm is the national tree of the United Arab Emirates.'}
];

export const clothing=[
{name:'Kandura',arabic:'الكندورة',image:'https://images.unsplash.com/photo-1780601247035-e34a7b06d35b?auto=format&fit=crop&w=1200&q=85',description:'The traditional white robe worn by Emirati men, also known as a dishdasha in other Gulf countries.',details:'The kandura is typically white, made from lightweight fabric suited to the hot climate. It has a collar (tarboush) and is often worn with a ghutra (headscarf) and agal (head rope). The length and style can indicate the wearer\'s origin.',significance:'The kandura represents Emirati identity and is worn daily by men across the UAE.'},
{name:'Ghutra',arabic:'الغترة',image:'https://images.unsplash.com/photo-1780831768363-73b4ea0eea48?auto=format&fit=crop&w=1200&q=85',description:'The traditional headscarf worn by Emirati men, usually white or red-and-white checkered.',details:'The ghutra protects the head and face from sun and sand. It is held in place by the agal (black rope). The way it is worn can vary by occasion and personal style.',significance:'The ghutra is an essential part of traditional Emirati male dress, providing both practical and cultural functions.'},
{name:'Agal',arabic:'العقال',image:'https://images.unsplash.com/photo-1780831768850-a650936de831?auto=format&fit=crop&w=1200&q=85',description:'The black cord worn over the ghutra to hold it in place on the head.',details:'The agal is a black cord band that secures the ghutra. While typically black, it can vary in style. It is an essential accessory to the traditional male headdress.',significance:'The agal completes the traditional Emirati male headwear and is a symbol of cultural identity.'},
{name:'Abaya',arabic:'العباية',image:'https://images.unsplash.com/photo-1728487235101-664d87965931?auto=format&fit=crop&w=1200&q=85',description:'A loose, flowing black robe worn by Emirati women over their clothing.',details:'The abaya is typically black but can feature intricate embroidery and embellishments, especially for special occasions. Modern abayas come in various styles and designs while maintaining the traditional loose fit.',significance:'The abaya is a symbol of modesty and cultural identity for Emirati women, worn with pride and style.'},
{name:'Shayla',arabic:'الشيلة',image:'https://images.unsplash.com/photo-1510495631661-903668f58af2?auto=format&fit=crop&w=1200&q=85',description:'A headscarf worn by Emirati women, draped around the head and shoulders.',details:'The shayla is a lightweight scarf, usually black or in subtle colors, worn with the abaya. It covers the hair and is styled in various ways.',significance:'The shayla is an essential part of traditional Emirati female dress, complementing the abaya.'}
];

export const architecture=[
{title:'Barasti Houses',image:'https://images.unsplash.com/photo-1536564397506-55dda737cc65?auto=format&fit=crop&w=1200&q=85',description:'Traditional houses made from palm fronds (barasti), used by coastal and desert communities.',details:'Barasti houses were constructed from palm fronds woven together. They were lightweight, portable, and well-suited to the climate, providing shade while allowing air circulation. This type of housing was common among Bedouin and coastal communities.'},
{title:'Wind Towers (Barjeel)',image:'https://images.unsplash.com/photo-1785508145125-b9dea49bea1b?auto=format&fit=crop&w=1200&q=85',description:'Traditional air conditioning systems that captured and directed breezes into buildings.',details:'Wind towers (barjeel) are a distinctive feature of traditional Gulf architecture. They catch breezes from any direction and channel cool air down into the building while expelling warm air. They are the architectural ancestors of modern air conditioning.'},
{title:'Coral Stone Houses',image:'https://images.unsplash.com/photo-1653763843954-0ad7300268a6?auto=format&fit=crop&w=1200&q=85',description:'Houses built from coral stone and gypsum, used in coastal settlements.',details:'Coastal communities built houses from coral stone quarried from the sea floor, bound with gypsum mortar. These houses were durable and provided natural insulation, keeping interiors cool in summer and warm in winter.'},
{title:'Forts and Watchtowers',image:'https://images.unsplash.com/photo-1674456944741-d9b8d523efa4?auto=format&fit=crop&w=1200&q=85',description:'Defensive structures built to protect settlements and trade routes.',details:'Forts were built using stone, mud brick, and gypsum, serving as residences for ruling families, defensive positions, and refuges during conflicts. Watchtowers provided early warning of approaching threats. Many have been restored and now serve as museums.'},
{title:'Traditional Mosques',image:'https://images.unsplash.com/photo-1583771803077-e512cbd2059c?auto=format&fit=crop&w=1200&q=85',description:'Simple but elegant mosques built using local materials and traditional techniques.',details:'Traditional mosques were built with coral stone, gypsum, and palm fronds. They featured simple prayer halls and, in some cases, wind towers for ventilation. Al Bidyah Mosque in Fujairah is the oldest surviving mosque in the UAE.'},
{title:'Modern UAE Architecture',image:'https://images.unsplash.com/photo-1667592441284-b590021411e3?auto=format&fit=crop&w=1200&q=85',description:'Contemporary architecture that blends traditional elements with cutting-edge design.',details:'Modern UAE architecture combines traditional Islamic design principles with innovative engineering. Buildings like the Burj Khalifa, Museum of the Future, and Louvre Abu Dhabi represent the UAE\'s architectural ambition on the world stage.'}
];

export const musicPoetry=[
{title:'Al Ayala',arabic:'العيالة',image:'https://media.db.com/images/public/6a7c883244b0c2e59e05c109/5d0631d0e_generated_image.png',description:'A traditional cultural performance involving two rows of men performing synchronized movements with sticks, accompanied by drumming and chanting.',details:'Al Ayala is a traditional Emirati performance art where two rows of performers face each other, waving sticks and chanting to the rhythm of drums. It is performed at weddings, national celebrations, and cultural events. UNESCO recognized Al Ayala as Intangible Cultural Heritage in 2014.'},
{title:'Traditional Instruments',image:'https://images.unsplash.com/photo-1680425982124-beaa3e9d3191?auto=format&fit=crop&w=1200&q=85',description:'Instruments used in traditional Emirati music include various types of drums and wind instruments.',details:'Key instruments include the mirwas (a small hand drum), the tabl (a larger drum), and the yarghul (a type of flute). These instruments accompany traditional performances like Al Ayala and are essential to Emirati musical heritage.'},
{title:'Nabati Poetry',arabic:'الشعر النبطي',image:'https://images.unsplash.com/photo-1687754715959-41fed2161528?auto=format&fit=crop&w=1200&q=85',description:'A form of traditional Arabic poetry that originated with Bedouin communities, known for its accessibility and everyday themes.',details:'Nabati poetry is a vernacular form of Arabic poetry that uses everyday language rather than classical Arabic. It covers themes of love, nature, daily life, and social commentary. It has been a vital form of cultural expression in the UAE for centuries.'},
{title:'Oral Traditions',image:'https://images.unsplash.com/photo-1655713532401-c5df95bc6e96?auto=format&fit=crop&w=1200&q=85',description:'Storytelling and oral traditions that passed history, values, and entertainment through generations.',details:'Before widespread literacy, oral traditions were the primary means of preserving history, sharing stories, and entertaining. Elders would recount tales of desert life, pearl diving, and historical events, keeping the community\'s heritage alive through spoken word.'}
];

export const nationalSymbols=[
{symbol:'UAE Flag',arabic:'علم الإمارات',image:'https://images.unsplash.com/photo-1518684079-3c830dcef0fd?auto=format&fit=crop&w=1200&q=85',description:'The flag of the United Arab Emirates was adopted on December 2, 1971, the day the UAE was founded.',details:'The flag features four colors: red, green, white, and black. Red represents courage and strength, green represents hope and prosperity, white represents peace and purity, and black represents the strength of the nation. The flag was designed by a young Emirati student, Abdullah Mohammed Al Maainah.'},
{symbol:'Coat of Arms',arabic:'شعار الإمارات',image:'https://images.unsplash.com/photo-1730626480563-10d80cab5201?auto=format&fit=crop&w=1200&q=85',description:'The UAE coat of arms features a golden falcon, the national bird, with a disc displaying the UAE flag surrounded by seven stars.',details:'The golden falcon represents the UAE\'s heritage of falconry and strength. The seven stars represent the seven emirates that form the federation. The falcon holds a parchment inscribed with the name of the country in Arabic.'},
{symbol:'National Anthem',arabic:'النشيد الوطني',image:'https://images.unsplash.com/photo-1564507060528-2545673c9e63?auto=format&fit=crop&w=1200&q=85',description:'"Ishy Bilady" (Long Live My Nation) is the national anthem of the UAE.',details:'The anthem was composed by Mohammed Abdel Wahab and the lyrics were written by Aref Al Sheikh Abdullah Al Hassan. It expresses love for the nation and commitment to its prosperity and protection.'},
{symbol:'National Bird',arabic:'الطائر الوطني',image:'https://images.unsplash.com/photo-1686918269961-507270a5a238?auto=format&fit=crop&w=1200&q=85',description:'The falcon is the national bird of the UAE, representing heritage, courage, and the traditional sport of falconry.',details:'The falcon has been a symbol of Emirati culture for centuries, central to the traditional sport of falconry. The saker falcon and peregrine falcon are particularly valued. The UAE has established world-class falcon hospitals and conservation programs.'},
{symbol:'National Tree',arabic:'الشجرة الوطنية',image:'https://images.unsplash.com/photo-1648814037760-1dd4d3169a26?auto=format&fit=crop&w=1200&q=85',description:'The date palm (ghaf in some contexts, but specifically the date palm) is the national tree of the UAE.',details:'The date palm has been essential to life in the Arabian Peninsula for thousands of years, providing food, shade, and materials. The UAE has millions of date palms, and dates are an important cultural and economic product.'},
{symbol:'National Animal',arabic:'الحيوان الوطني',image:'https://images.unsplash.com/photo-1626526153942-19c8f9775cc4?auto=format&fit=crop&w=1200&q=85',description:'The Arabian Oryx is the national animal of the UAE, representing conservation success.',details:'The Arabian Oryx was once extinct in the wild but was successfully reintroduced through conservation programs, including efforts in the UAE. Sir Bani Yas Island played a key role in the species\' recovery.'}
];

// Override all culture images from the centralized registry (src/data/images.js).
const _heritageSlugs = { 'Falconry': 'falconry', 'Camel Racing': 'camel-racing', 'Pearl Diving': 'pearl-diving', 'Dhow Building': 'dhow-building', 'Traditional Weaving (Sadu)': 'sadu-weaving', 'Henna': 'henna' };
heritage.forEach(h => { const s = _heritageSlugs[h.title]; if (s && cultureImages[s]) h.image = cultureImages[s]; });
const _cuisineSlugs = { 'Machboos': 'machboos', 'Harees': 'harees', 'Luqaimat': 'luqaimat', 'Balaleet': 'balaleet', 'Arabic Coffee (Gahwa)': 'arabic-coffee', 'Dates': 'dates' };
cuisine.forEach(c => { const s = _cuisineSlugs[c.name]; if (s && cultureImages[s]) c.image = cultureImages[s]; });
const _clothingSlugs = { 'Kandura': 'kandura', 'Ghutra': 'ghutra', 'Agal': 'agal', 'Abaya': 'abaya', 'Shayla': 'shayla' };
clothing.forEach(c => { const s = _clothingSlugs[c.name]; if (s && cultureImages[s]) c.image = cultureImages[s]; });
const _archSlugs = { 'Barasti Houses': 'barasti-houses', 'Wind Towers (Barjeel)': 'wind-towers', 'Coral Stone Houses': 'coral-stone-houses', 'Forts and Watchtowers': 'forts-and-watchtowers', 'Traditional Mosques': 'traditional-mosques', 'Modern UAE Architecture': 'modern-architecture' };
architecture.forEach(a => { const s = _archSlugs[a.title]; if (s && cultureImages[s]) a.image = cultureImages[s]; });
const _musicSlugs = { 'Al Ayala': 'al-ayala', 'Traditional Instruments': 'traditional-instruments', 'Nabati Poetry': 'nabati-poetry', 'Oral Traditions': 'oral-traditions' };
musicPoetry.forEach(m => { const s = _musicSlugs[m.title]; if (s && cultureImages[s]) m.image = cultureImages[s]; });
const _symbolSlugs = { 'UAE Flag': 'uae-flag', 'Coat of Arms': 'coat-of-arms', 'National Anthem': 'national-anthem', 'National Bird': 'national-bird', 'National Tree': 'national-tree', 'National Animal': 'national-animal' };
nationalSymbols.forEach(s => { const slug = _symbolSlugs[s.symbol]; if (slug && cultureImages[slug]) s.image = cultureImages[slug]; });