import { locationImages, uaemapimg } from './images';

export const puzzleStages = [
  {
    id: 'uae',
    title: 'Build the UAE',
    subtitle: 'Bring the seven emirates together.',
    type: 'image',
    image: uaemapimg.map,
    pieces: 48,
    facts: ['The UAE has seven emirates.', 'Abu Dhabi is the capital.', 'The UAE was formed in 1971.'],
  },
  {
    id: 'abu-dhabi',
    title: 'Abu Dhabi',
    subtitle: 'Discover the capital’s landmark mosque.',
    type: 'image',
    image: locationImages['sheikh-zayed-grand-mosque'],
    pieces: 48,
    facts: ['Capital of the UAE.', 'Home to Sheikh Zayed Grand Mosque.', 'The largest emirate by area.'],
    icon: '🕌',
  },
  {
    id: 'dubai',
    title: 'Dubai',
    subtitle: 'Piece together a city reaching for the sky.',
    type: 'image',
    image: locationImages['burj-khalifa'],
    pieces: 48,
    facts: ['Home to the world’s tallest building.', 'The Burj Khalifa opened in 2010.', 'Dubai Creek is part of the city’s historic heart.'],
    icon: '🏙️',
  },
  {
    id: 'sharjah',
    title: 'Sharjah',
    subtitle: 'Explore a city shaped by heritage.',
    type: 'image',
    image: locationImages['heart-of-sharjah'],
    pieces: 48,
    facts: ['Known as the UAE’s cultural capital.', 'Sharjah borders two gulfs.', 'Its heritage district preserves historic homes.'],
    icon: '🏛️',
  },
  {
    id: 'ajman',
    title: 'Ajman',
    subtitle: 'Follow the coast along the Corniche.',
    type: 'image',
    image: locationImages['ajman-corniche'],
    pieces: 48,
    facts: ['The smallest emirate by area.', 'Ajman has a long Arabian Gulf coastline.', 'Al Zorah is known for its mangroves.'],
    icon: '⛵',
  },
  {
    id: 'umm-al-quwain',
    title: 'Umm Al Quwain',
    subtitle: 'Discover quiet shores and mangroves.',
    type: 'image',
    image: locationImages['uaq-mangrove-reserve'],
    pieces: 48,
    facts: ['Often shortened to UAQ.', 'Its coast includes extensive mangroves.', 'Traditional dhow sailing is part of its heritage.'],
    icon: '🌊',
  },
  {
    id: 'ras-al-khaimah',
    title: 'Ras Al Khaimah',
    subtitle: 'Climb into the northern mountains.',
    type: 'image',
    image: locationImages['jebel-jais'],
    pieces: 48,
    facts: ['Home to Jebel Jais, the UAE’s highest mountain.', 'The emirate lies in the north of the UAE.', 'Its history includes ancient pearling traditions.'],
    icon: '⛰️',
  },
  {
    id: 'fujairah',
    title: 'Fujairah',
    subtitle: 'Finish the journey on the east coast.',
    type: 'image',
    image: locationImages['fujairah-fort'],
    pieces: 48,
    facts: ['Fujairah faces the Gulf of Oman.', 'The historic fort overlooks the city.', 'The Hajar Mountains run through the emirate.'],
    icon: '🏰',
  },
];