import { timelineImages } from './images';
export const timelineEvents=[
{era:'Ancient UAE',year:'~8,000 BCE',title:'Earliest Human Settlement',type:'📜',description:'Archaeological evidence at sites like Mleiha shows human habitation in the region dating back over 8,000 years, with Stone Age communities establishing settlements.',importance:'These findings demonstrate that the land now known as the UAE has been continuously inhabited for millennia, connecting the modern nation to a deep ancient heritage.',relatedPlace:'Mleiha Archaeological Centre',relatedTopic:'UAE History'},
{era:'Ancient UAE',year:'~2600-2000 BCE',title:'Umm an-Nar Culture',type:'📜',description:'The Umm an-Nar culture flourished, characterized by circular tombs, advanced pottery, and extensive trade networks connecting the region with Mesopotamia and the Indus Valley.',importance:'The Umm an-Nar period represents one of the earliest civilizations in the region, with evidence of international trade and sophisticated social organization.',relatedPlace:'Tell Abraq',relatedTopic:'UAE History'},
{era:'Ancient UAE',year:'~1300-300 BCE',title:'Wadi Suq and Late Bronze Age',type:'📜',description:'The Wadi Suq period followed the Umm an-Nar culture, with continued settlement and trade. Archaeological sites from this period show evolving burial practices and metalwork.',importance:'This period shows the continuity of settlement and cultural development in the region between the Bronze and Iron Ages.',relatedPlace:'Shimal',relatedTopic:'UAE History'},
{era:'Ancient UAE',year:'~300 BCE-300 CE',title:'Mleiha Settlement',type:'📜',description:'The settlement at Mleiha flourished during the late pre-Islamic period, with evidence of a fortified building, coin minting, and trade connections across the region.',importance:'Mleiha provides evidence of an organized, prosperous settlement with its own coinage and extensive trade networks during the pre-Islamic period.',relatedPlace:'Mleiha Archaeological Centre',relatedTopic:'UAE History'},
{era:'Traditional UAE',year:'~1700s-1930s',title:'Pearl Diving Era',type:'📜',image:'https://images.unsplash.com/photo-1588408687414-434a389defac?auto=format&fit=crop&w=1200&q=85',description:'Pearl diving became the economic backbone of coastal communities. Divers would hold their breath to collect oysters, facing dangers including drowning and shark attacks. The pearling season ran from June to September.',importance:'Pearl diving shaped the culture, economy, and social structure of UAE coastal communities for centuries, fostering trade relationships across the Gulf.',relatedPlace:'Al Jazirah Al Hamra',relatedTopic:'Pearl Diving'},
{era:'Traditional UAE',year:'~1700s-1900s',title:'Dhow Building and Maritime Trade',type:'🏗',description:'Traditional dhow building supported trade across the Gulf and Indian Ocean. Shipwrights built seaworthy vessels without blueprints, relying on knowledge passed down through generations.',importance:'Dhow building enabled the trade networks that connected the UAE to the wider world and represents the maritime heritage of the region.',relatedPlace:'Dubai Creek',relatedTopic:'Dhow Building'},
{era:'Traditional UAE',year:'~1700s-1900s',title:'Bedouin Life and Oasis Agriculture',type:'📜',description:'Bedouin communities practiced nomadic herding in the desert, while oasis communities at Al Ain and other locations used the falaj irrigation system for agriculture.',importance:'Bedouin and oasis traditions shaped the cultural identity of the UAE, including values of hospitality, resilience, and community.',relatedPlace:'Al Ain Oasis',relatedTopic:'UAE Heritage'},
{era:'Trucial States',year:'1820',title:'Trucial States Begin',type:'📜',description:'The General Maritime Treaty of 1820 established a relationship between Britain and the coastal sheikhdoms of the region, which became known as the Trucial States.',importance:'The Trucial States period shaped the political development of the region and set the stage for the eventual formation of the UAE.',relatedPlace:'Dhayah Fort',relatedTopic:'UAE History'},
{era:'Trucial States',year:'1892',title:'Exclusive Agreements',type:'📜',description:'The Trucial States signed exclusive agreements with Britain, under which Britain managed their foreign relations and defense in exchange for protection.',importance:'These agreements defined the political framework of the Trucial States until the process of forming an independent federation began in the late 1960s.',relatedPlace:'Sharjah Fort',relatedTopic:'UAE History'},
{era:'Oil Era',year:'1958',title:'Oil Discovery',type:'🔬',image:'https://images.unsplash.com/photo-1694431452845-719ff1e1eea9?auto=format&fit=crop&w=1200&q=85',description:'Oil was discovered in Abu Dhabi in 1958, with commercial exports beginning in 1963. This discovery would transform the economy and society of the region.',importance:'The discovery of oil began the economic transformation that would fund the rapid development of the UAE after independence.',relatedPlace:'Abu Dhabi',relatedTopic:'UAE History'},
{era:'Oil Era',year:'1960s',title:'Infrastructure and Education Development',type:'🏗',description:'Using oil revenues, the Trucial States began investing in infrastructure, schools, hospitals, and roads, laying the foundation for modern development.',importance:'These investments in education and infrastructure were essential preparations for the formation and development of the independent UAE.',relatedPlace:'Abu Dhabi',relatedTopic:'UAE History'},
{era:'1971',year:'December 2, 1971',title:'Formation of the United Arab Emirates',type:'🏆',image:'https://images.unsplash.com/photo-1546412414-8035e1776c9a?auto=format&fit=crop&w=1200&q=85',description:'Six emirates — Abu Dhabi, Dubai, Sharjah, Ajman, Umm Al Quwain, and Fujairah — agreed to form a federation. Sheikh Zayed bin Sultan Al Nahyan of Abu Dhabi and Sheikh Rashid bin Saeed Al Maktoum of Dubai were key architects of the union. Ras Al Khaimah joined on February 10, 1972.',importance:'The formation of the UAE was a historic moment that united seven emirates into one nation, creating a federation that would become one of the most successful in the world.',relatedPlace:'Etihad Museum',relatedTopic:'National Day'},
{era:'Post-1971',year:'1970s-1980s',title:'Rapid Development',type:'🏗',description:'Under the leadership of Sheikh Zayed, the UAE invested oil revenues in infrastructure, education, healthcare, housing, and public services, transforming the country at an unprecedented pace.',importance:'This period of rapid development established the modern infrastructure and institutions that define the UAE today.',relatedPlace:'Abu Dhabi Corniche',relatedTopic:'UAE History'},
{era:'Post-1971',year:'1985',title:'Emirates Airline Founded',type:'🏆',description:'Emirates Airline was founded in 1985 with just two aircraft. It would grow into one of the world\'s largest and most respected airlines, connecting Dubai to the world.',importance:'Emirates became a symbol of UAE ambition and a key driver of tourism and trade, connecting Dubai to destinations worldwide.',relatedPlace:'Dubai',relatedTopic:'UAE Achievements'},
{era:'Post-1971',year:'1997',title:'Sharjah Art Museum Opens',type:'🏛',description:'The Sharjah Art Museum opened, becoming the largest art museum in the Gulf region and reinforcing Sharjah\'s position as a cultural capital.',importance:'The museum demonstrated the UAE\'s commitment to cultural development and the arts alongside economic growth.',relatedPlace:'Sharjah Art Museum',relatedTopic:'Culture'},
{era:'Modern UAE',year:'2007',title:'Sheikh Zayed Grand Mosque Opens',type:'🏛',image:'https://images.unsplash.com/photo-1564507060528-2545673c9e63?auto=format&fit=crop&w=1200&q=85',description:'The Sheikh Zayed Grand Mosque, one of the world\'s largest mosques, was completed and opened in Abu Dhabi, becoming a symbol of Islamic culture and tolerance.',importance:'The mosque became one of the UAE\'s most visited landmarks, welcoming people of all faiths and symbolizing the nation\'s cultural and religious heritage.',relatedPlace:'Sheikh Zayed Grand Mosque',relatedTopic:'Culture'},
{era:'Modern UAE',year:'2010',title:'Burj Khalifa Opens',type:'🏆',image:'https://images.unsplash.com/photo-1512453973666-147629fde45a?auto=format&fit=crop&w=1200&q=85',description:'The Burj Khalifa, the world\'s tallest building at 828 metres, opened in Dubai, becoming an iconic symbol of the UAE\'s ambition and engineering achievement.',importance:'The Burj Khalifa became a global icon of modern Dubai and a symbol of the UAE\'s ability to achieve world-first achievements.',relatedPlace:'Burj Khalifa',relatedTopic:'UAE Achievements'},
{era:'Modern UAE',year:'2017',title:'Louvre Abu Dhabi Opens',type:'🏛',image:'https://images.unsplash.com/photo-1672324016837-4b803c38fc95?auto=format&fit=crop&w=1200&q=85',description:'The Louvre Abu Dhabi opened as the first universal museum in the Arab world, bridging Eastern and Western art and culture.',importance:'The museum positioned Abu Dhabi as a global cultural destination and demonstrated the UAE\'s commitment to cultural exchange.',relatedPlace:'Louvre Abu Dhabi',relatedTopic:'Culture'},
{era:'Modern UAE',year:'2020',title:'Hope Probe Mission',type:'🚀',image:'https://images.unsplash.com/photo-1667592441284-b590021411e3?auto=format&fit=crop&w=1200&q=85',description:'The UAE launched the Hope Probe to Mars, making the UAE the first Arab country and the fifth in the world to reach Mars. The mission was timed to coincide with the UAE\'s 50th anniversary.',importance:'The Hope Probe demonstrated the UAE\'s space ambitions and inspired a new generation of scientists and engineers across the Arab world.',relatedPlace:'Museum of the Future',relatedTopic:'UAE Achievements'},
{era:'Modern UAE',year:'2021',title:'Net Zero 2050 Commitment',type:'🌱',description:'The UAE became the first Middle Eastern country to commit to net zero emissions by 2050, a major climate commitment.',importance:'This commitment positioned the UAE as a leader in climate action in the region and drove investment in renewable energy and sustainability.',relatedPlace:'Masdar City',relatedTopic:'Sustainability'},
{era:'Modern UAE',year:'2022',title:'Museum of the Future Opens',type:'🏆',image:'https://images.unsplash.com/photo-1687754715959-41fed2161528?auto=format&fit=crop&w=1200&q=85',description:'The Museum of the Future opened in Dubai, with its distinctive Arabic calligraphy facade and focus on future technologies and innovation.',importance:'The museum became a symbol of the UAE\'s forward-looking vision and its commitment to shaping the future through innovation.',relatedPlace:'Museum of the Future',relatedTopic:'UAE Achievements'},
{era:'Modern UAE',year:'2023',title:'Etihad Rail National Network Opens',type:'🚆',image:'https://www.mepmiddleeast.com/cloud/2025/01/24/ORFUAFLRJ5GGDN4IYMCZIUSGFA-1.png',description:'The UAE inaugurated the Etihad Rail National Railway Network, a railway system spanning approximately 900 kilometres and connecting all seven emirates from Ghuwaifat to Fujairah. Freight operations were launched across the network, linking major centres of industry, trade, manufacturing and logistics.',importance:'Etihad Rail represents a major step in the UAE’s transport infrastructure, strengthening connections between the emirates, supporting trade and reducing reliance on road freight. The network also forms part of the UAE’s long-term vision for greater regional connectivity across the GCC.',relatedPlace:'Abu Dhabi',relatedTopic:'UAE Achievements'},
{era:'Modern UAE',year:'2023',title:'COP28 in Dubai',type:'🌍',image:'https://images.unsplash.com/photo-1647377129158-40daa63b2f51?auto=format&fit=crop&w=1200&q=85',description:'The UAE hosted COP28, the United Nations Climate Change Conference, bringing world leaders together to address the global climate crisis.',importance:'Hosting COP28 demonstrated the UAE\'s commitment to global climate action and its role as a bridge between nations on environmental issues.',relatedPlace:'Dubai',relatedTopic:'Sustainability'},
{era:'Future',year:'2050',title:'UAE Net Zero Target',type:'🌱',image:'https://images.unsplash.com/photo-1641852347240-9d64f5c7b8f2?auto=format&fit=crop&w=1200&q=85',description:'The UAE aims to achieve net zero greenhouse gas emissions by 2050 through renewable energy, efficiency improvements, and other climate actions.',importance:'This target drives the UAE\'s transition to a sustainable economy and positions it as a leader in climate action.',relatedPlace:'Masdar City',relatedTopic:'Sustainability'},
{era:'Future',year:'2117',title:'Mars 2117 Project',type:'🚀',description:'The Mars 2117 project envisions building a human settlement on Mars by 2117, representing the UAE\'s long-term ambition for space exploration.',importance:'The project inspires innovation and long-term thinking, positioning the UAE as a pioneer in space exploration and human achievement.',relatedPlace:'Museum of the Future',relatedTopic:'UAE Achievements'}
];

// Override timeline images from centralized registry (src/data/images.js).
const _timelineSlugs = { 'Pearl Diving Era': 'pearl-diving-era', 'Oil Discovery': 'oil-discovery', 'Formation of the United Arab Emirates': 'uae-formation', 'Sheikh Zayed Grand Mosque Opens': 'sheikh-zayed-mosque-opens', 'Burj Khalifa Opens': 'burj-khalifa-opens', 'Louvre Abu Dhabi Opens': 'louvre-opens', 'Hope Probe Mission': 'hope-probe', 'Museum of the Future Opens': 'museum-of-future-opens', 'COP28 in Dubai': 'cop28', 'UAE Net Zero Target': 'net-zero-2050' };
timelineEvents.forEach(e => { const s = _timelineSlugs[e.title]; if (s && timelineImages[s]) e.image = timelineImages[s]; });